package com.sistemabarberia.fadex_backend.modules.reclamo.entity.enums;

public enum TipoProblema {
    SERVICIO_DEFECTUOSO,
    CORTE_INCORRECTO,
    BARBERO_INCORRECTO,
    ATENCION_AL_CLIENTE,
    INCUMPLIMIENTO_HORARIO,
    DEMORA_EN_ATENCION,
    RESERVA_INCORRECTA,
    COBRO_INCORRECTO,
    PRODUCTO_DEFECTUOSO,
    PRODUCTO_INCORRECTO,
    PRODUCTO_INCOMPLETO,
    PRODUCTO_NO_LLEGO,
    DEMORA_EN_ENTREGA,
    OTRO
}