
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.lqzgedqjntomzubacvqi
spring.datasource.password=TF8D111CD207C

spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=1234

jwt.secret=b92b92ced5e768054fd5d7c19727efd701d1ea3db94a34eae1dd5f38c869bdf4
jwt.expiration=900000
logging.level.org.flywaydb=DEBUG

file.upload-dir=uploads/

server.port=8081


logging.level.com.sistemabarberia=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=DEBUG